#!/bin/sh
set -e
export LC_ALL=C
export CFLAGS="$CFLAGS -fno-tree-vectorize"
export CXXFLAGS="$CXXFLAGS -fno-tree-vectorize"

scripts/libxml2-config
scripts/libxml2-build "$@"
scripts/fribidi-config
scripts/fribidi-build "$@"
scripts/freetype2-config
scripts/freetype2-build "$@"
scripts/harfbuzz-config
scripts/harfbuzz-build "$@"
scripts/libplacebo-config
scripts/libplacebo-build "$@"
scripts/libass-config
scripts/libass-build "$@"
scripts/dav1d-config
scripts/dav1d-build "$@"
scripts/vvdec-config
scripts/vvdec-build "$@"
scripts/fdkaac-config
scripts/fdkaac-build "$@"
#scripts/libjxl-config
#scripts/libjxl-build "$@"
scripts/vkheader-config
scripts/vkheader-build "$@"
scripts/ffmpeg-config
scripts/ffmpeg-build "$@"
scripts/lua-config
scripts/lua-build "$@"
scripts/mpv-config
scripts/mpv-build "$@"
