#!/bin/sh
set -e

echo() { printf %s\\n "$*"; }  # depends on standard IFS (which we have)

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/ffmpeg_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/ffmpeg_options) "$@"
    unset -v IFS
fi

OPTIONS="--enable-gpl --enable-nonfree --disable-debug --enable-openssl --disable-doc --enable-static --disable-shared 
--enable-libfdk-aac --enable-libxml2 --enable-libvvdec --enable-libdav1d --extra-version=VVCEasy --pkg-config-flags="--static" --enable-pic --disable-audiotoolbox"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

echo Using ffmpeg options: $OPTIONS "$@"

mkdir -p "$BUILD"/ffmpeg_build
cd "$BUILD"/ffmpeg_build
# need to link against stdc++ in case libplacebo was built with glslang,
# which requires that
export LDFLAGS="$LDFLAGS -lstdc++"
"$BUILD"/ffmpeg/configure --prefix="$BUILD"/build_libs $OPTIONS "$@"
