#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/fribidi_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/fribidi_options) "$@"
    unset -v IFS
fi

OPTIONS="-Ddefault_library=static -Dtests=false -Ddemos=false"

cd "$BUILD"/fribidi

test -d build && OPTIONS="$OPTIONS --wipe"
echo Using fribidi options: $OPTIONS "$@"

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"
