#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/harfbuzz_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/harfbuzz_options) "$@"
    unset -v IFS
fi

OPTIONS="-Ddefault_library=static -Dtests=disabled -Ddocs=disabled"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/harfbuzz

test -d build && OPTIONS="$OPTIONS --wipe"
echo Using harfbuzz options: $OPTIONS "$@"

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"
