#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/libjxl_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libjxl_options) "$@"
    unset -v IFS
fi

OPTIONS="-DJPEGXL_ENABLE_JPEGLI_LIBJPEG=OFF -DJPEGXL_ENABLE_EXAMPLES=OFF -DJPEGXL_BUNDLE_LIBPNG=ON -DCMAKE_BUILD_TYPE=Release
-DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DJPEGXL_ENABLE_BENCHMARK=OFF -DJPEGXL_ENABLE_PLUGINS=ON
-DJPEGXL_ENABLE_MANPAGES=OFF -DJPEGXL_TEST_TOOLS=OFF"

cd "$BUILD"/libjxl
sed -i 's/-lm/-lm -lstdc++/g' lib/jxl/libjxl.pc.in lib/threads/libjxl_threads.pc.in
cmake -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" $OPTIONS . -GNinja "$@"
