#!/bin/sh
set -e

make -C lua MYCFLAGS="-fPIC -Dgetlocaledecpoint\(\)=\(\'.\'\)" PLAT=linux LUA_T= LUAC_T= LDFLAGS="-static" "$@"
cp lua/*.h "$BUILD/build_libs/include/"
cp lua/*.a "$BUILD/build_libs/lib/"
