#!/bin/sh
set -e

make -C lua MYCFLAGS="-fPIC -Dgetlocaledecpoint\(\)=\(\'.\'\)" PLAT=linux LUA_T= LUAC_T= "$@"
make -C lua INSTALL=${INSTALL:-install} INSTALL_TOP=$BUILD/build_libs TO_BIN=/dev/null install

cat >>$BUILD/build_libs/lib/pkgconfig/lua.pc <<'EOF'
Name: Lua
Description:
Version: ${version}
Libs: -L${libdir} -llua
Cflags: -I${includedir}
EOF
