#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"
case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

if test -f "$BUILD"/lua_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/lua_options) "$@"
    unset -v IFS
fi
