#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/vkheader_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/vkheader_options) "$@"
    unset -v IFS
fi

OPTIONS="-DCMAKE_BUILD_TYPE=Release"

cd "$BUILD"/Vulkan-Headers
mkdir -p build && cd build
cmake -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" $OPTIONS .. "$@"
