#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/vvdec_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/vvdec_options) "$@"
    unset -v IFS
fi

OPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_EXE_LINKER_FLAGS='-static' -DCMAKE_CXX_FLAGS='-fexceptions -frtti'"

cd "$BUILD"/vvdec
cmake -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" $OPTIONS . "$@"
